export const PRODUCT_FETCH_SUCCEEDED="PRODUCT_FETCH_SUCCEEDED"
export const PRODUCT_FETCH_FAILED="PRODUCT_FETCH_FAILED"
export const PRODUCT_FETCH_REQUESTED= "PRODUCT_FETCH_REQUESTED"

export const PRODUCT_FETCH_BY_ID_SUCCEEDED="PRODUCT_FETCH_BY_ID__SUCCEEDED"
export const PRODUCT_FETCH_BY_ID_FAILED="PRODUCT_FETCH_BY_ID__FAILED"
export const PRODUCT_FETCH_BY_ID_REQUESTED= "PRODUCT_FETCH_BY_ID__REQUESTED"